-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Cliente"
(
    id integer NOT NULL,
    "Rg" character varying(7) NOT NULL,
    "Nome" character varying(20) NOT NULL,
    "Telefone" character varying(12) NOT NULL,
    "Email" character varying(30) NOT NULL,
    "Logradouro" character varying(10) NOT NULL,
    "Numero" integer NOT NULL,
    "Complemento" character varying(15) NOT NULL,
    id_bairro integer NOT NULL,
    id_municipio integer NOT NULL,
    id_tipo_logradouro integer NOT NULL,
    id_uf integer NOT NULL,
    CONSTRAINT "Cliente_rg" PRIMARY KEY (id_bairro)
);

CREATE TABLE IF NOT EXISTS public."Bairro"
(
    id integer NOT NULL,
    nome character varying(10) NOT NULL,
    municipio_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Municipio"
(
    id integer NOT NULL,
    "Nome" character varying(15) NOT NULL,
    uf_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Tipo logradouro"
(
    id integer NOT NULL,
    "Nome" character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Uf"
(
    id integer NOT NULL,
    nome character varying(15) NOT NULL,
    "Sigla" character varying(2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Produto"
(
    id integer NOT NULL,
    "Nome" character varying(25) NOT NULL,
    id_tipo_produto integer NOT NULL,
    id_estoque integer NOT NULL,
    PRIMARY KEY (id_tipo_produto)
);

CREATE TABLE IF NOT EXISTS public."Tipo produto"
(
    id integer NOT NULL,
    nome character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Estoque"
(
    id integer NOT NULL,
    "Quantidade" integer NOT NULL,
    id_produto integer NOT NULL,
    PRIMARY KEY (id_produto)
);

CREATE TABLE IF NOT EXISTS public."Preco"
(
    "Data" date NOT NULL,
    "Preco_prod" integer NOT NULL,
    id_produto integer NOT NULL,
    PRIMARY KEY ("Data")
);

CREATE TABLE IF NOT EXISTS public."Compra"
(
    "Data" date NOT NULL,
    "QTDE_comprada" integer NOT NULL,
    id_cliente integer NOT NULL,
    id_produto integer NOT NULL,
    PRIMARY KEY ("Data")
);

ALTER TABLE IF EXISTS public."Cliente"
    ADD CONSTRAINT "FK_bairro_cliente" FOREIGN KEY (id_bairro)
    REFERENCES public."Bairro" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cliente"
    ADD CONSTRAINT "FK_municipio_cliente" FOREIGN KEY (id_municipio)
    REFERENCES public."Municipio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cliente"
    ADD CONSTRAINT "FK_tipo_logradouro_cliente" FOREIGN KEY (id_tipo_logradouro)
    REFERENCES public."Tipo logradouro" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Cliente"
    ADD CONSTRAINT "FK_uf_cliente" FOREIGN KEY (id_uf)
    REFERENCES public."Uf" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bairro"
    ADD CONSTRAINT "FK_municipio_bairro" FOREIGN KEY (municipio_id)
    REFERENCES public."Municipio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Municipio"
    ADD CONSTRAINT "FK_uf_municipio" FOREIGN KEY (uf_id)
    REFERENCES public."Uf" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Produto"
    ADD CONSTRAINT "FK_tipo_produto_produto" FOREIGN KEY (id_tipo_produto)
    REFERENCES public."Tipo produto" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Produto"
    ADD CONSTRAINT "FK_estoque_produto" FOREIGN KEY (id_estoque)
    REFERENCES public."Estoque" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Estoque"
    ADD CONSTRAINT "FK_produto_estoque" FOREIGN KEY (id_produto)
    REFERENCES public."Produto" (id_estoque) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Preco"
    ADD CONSTRAINT "FK_produto_preco" FOREIGN KEY (id_produto)
    REFERENCES public."Produto" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Compra"
    ADD CONSTRAINT "FK_produto_compra" FOREIGN KEY (id_produto)
    REFERENCES public."Produto" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Compra"
    ADD CONSTRAINT "FK_cliente_compra" FOREIGN KEY (id_cliente)
    REFERENCES public."Cliente" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;